version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    depends_on:
      - db
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
