version: '3'

services:
  go_server:
    build: 
      context: ./go
    ports:
      - "5000:5000"
    networks:
      - app-network

  python_client:
    build: 
      context: ./python
    depends_on:
      - go_server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
